import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head className={styles.header}>
        <title>Spotify Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Spotify Dashboard
        </h1>

        <p className={styles.description}>
          A mini project using {' '}
          <code className={styles.code}>Next.js</code>
        </p>
        
        <div className={styles.grid}>

          <Link href="/sub/user-search">
            <a  className={styles.card}>
              <h2>User Search</h2>
              <div>Search for Users using their Spotify ID to see their favourites and playlists.</div>
            </a>
          </Link>

          <Link href="/sub/song-search">
            <a className={styles.card}>
              <div>
                <h2>Search Music</h2>
                Search for artists, albums, top-tracks, playlists, and new-releases from Spotify's API
              </div>
            </a>
          </Link>

        </div>
      </main>

      <footer className={styles.footer}>
        
          Made with {' '}
          <span className={styles.logo}>
            <Image src="/nextjs.svg" alt="Next.js Logo" width={60} height={30} />
          </span>
        
      </footer>
    </div>
  )
}
